#INCLUDE "P16F877A.INC"  ;

__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_OFF & _BODEN_OFF & _LVP_OFF & _HS_OSC ; 
	
REG1	    EQU 0X20 ;
REG2	    EQU 0X21 ;
REG3	    EQU 0X22 ;
TEMP	    EQU 0X23 ;
	
ORG 0x00
 
CONFI	BSF STATUS,RP0
	MOVLW H'00'
	MOVWF TRISD	;PORT D OUTPUT
	MOVLW H'FF'
	MOVWF TRISC	;PORT C USART MODE
	MOVLW D'12'
	MOVWF SPBRG
	MOVLW H'30'	; Synchronous slave,8-bit recieve
	MOVWF TXSTA
	BCF STATUS,RP0
	MOVLW H'90'	; Synchronous slave,8-bit recieve
	MOVWF RCSTA
	
MAIN	BTFSS PIR1,RCIF	 ; TEST IF RCIF IS READY
	GOTO MAIN	 ; KEEP ON TESTING IF EMPTY
	MOVF RCREG,W 	 ; ELSE START RECIEVING DATA
	MOVWF PORTD
	
END
